# Generated by Django 5.2.6 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
    ]
