# Generated by Django 5.2.6 on 2026-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0002_staff_services'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('RECEPTIONIST', 'Receptionist')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='services.service'),
        ),
    ]
