# Generated by Django 5.2.6 on 2026-09-12 16:37

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0006_alter_staff_user'),
        ('staffleave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffleave',
            name='leave_date',
        ),
        migrations.AddField(
            model_name='staffleave',
            name='from_date',
            field=models.DateField(default='2026-09-01'),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='to_date',
            field=models.DateField(default='2026-09-01'),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='staffleave',
            constraint=models.CheckConstraint(condition=models.Q(('from_date__lte', models.F('to_date'))), name='from_date_not_greater_than_to_date'),
        ),
    ]
