# Generated by Django 5.2.6 on 2026-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffleave', '0002_remove_staffleave_leave_date_staffleave_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffleave',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='staffleave',
            name='to_date',
            field=models.DateField(),
        ),
    ]
