# Generated by Django 5.2.6 on 2026-08-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_name', models.CharField(max_length=255)),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('NATIONAL', 'Naional'), ('REGIONAL', 'Regional'), ('RELIGIOUS', 'Religious'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='BUSINESS', max_length=10)),
                ('is_full_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='business.business')),
            ],
        ),
    ]
