# Generated by Django 5.2.6 on 2026-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_timezone'),
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_type',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('RELIGIOUS', 'Religious'), ('BUSINESS', 'Business'), ('OTHER', 'Other')], default='BUSINESS', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('business', 'holiday_date')},
        ),
    ]
