# Generated by Django 5.2.6 on 2026-09-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_alter_holiday_holiday_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='is_full_day',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='start_time',
        ),
    ]
