# Generated by Django 5.2.6 on 2026-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='timezone',
        ),
        migrations.AddField(
            model_name='business',
            name='require_customer_details',
            field=models.BooleanField(default=False),
        ),
    ]
