# Generated by Django 5.2.6 on 2026-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BUSINESS_OWNER', 'Business Owner'), ('STAFF', 'Staff')], default='STAFF', max_length=30),
        ),
    ]
